"""initial_schema

Revision ID: f6e45abff578
Revises: 
Create Date: 2026-07-01 16:28:55.723264

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f6e45abff578'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('incidents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rule_name', sa.String(), nullable=False),
    sa.Column('severity', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('mitre_technique', sa.String(), nullable=True),
    sa.Column('mitre_tactic', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('affected_user', sa.String(), nullable=True),
    sa.Column('affected_ip', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_incidents_affected_ip'), 'incidents', ['affected_ip'], unique=False)
    op.create_index(op.f('ix_incidents_affected_user'), 'incidents', ['affected_user'], unique=False)
    op.create_index(op.f('ix_incidents_id'), 'incidents', ['id'], unique=False)
    op.create_index(op.f('ix_incidents_mitre_tactic'), 'incidents', ['mitre_tactic'], unique=False)
    op.create_index(op.f('ix_incidents_mitre_technique'), 'incidents', ['mitre_technique'], unique=False)
    op.create_index(op.f('ix_incidents_rule_name'), 'incidents', ['rule_name'], unique=False)
    op.create_index(op.f('ix_incidents_severity'), 'incidents', ['severity'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('log_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('file_url', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('uploaded_by', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_log_files_id'), 'log_files', ['id'], unique=False)
    op.create_table('log_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('severity', sa.String(), nullable=True),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('user_name', sa.String(), nullable=True),
    sa.Column('hostname', sa.String(), nullable=True),
    sa.Column('event_id', sa.String(), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('parsed_json', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['file_id'], ['log_files.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_log_entries_event_id'), 'log_entries', ['event_id'], unique=False)
    op.create_index(op.f('ix_log_entries_hostname'), 'log_entries', ['hostname'], unique=False)
    op.create_index(op.f('ix_log_entries_id'), 'log_entries', ['id'], unique=False)
    op.create_index(op.f('ix_log_entries_ip_address'), 'log_entries', ['ip_address'], unique=False)
    op.create_index(op.f('ix_log_entries_severity'), 'log_entries', ['severity'], unique=False)
    op.create_index(op.f('ix_log_entries_user_name'), 'log_entries', ['user_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_log_entries_user_name'), table_name='log_entries')
    op.drop_index(op.f('ix_log_entries_severity'), table_name='log_entries')
    op.drop_index(op.f('ix_log_entries_ip_address'), table_name='log_entries')
    op.drop_index(op.f('ix_log_entries_id'), table_name='log_entries')
    op.drop_index(op.f('ix_log_entries_hostname'), table_name='log_entries')
    op.drop_index(op.f('ix_log_entries_event_id'), table_name='log_entries')
    op.drop_table('log_entries')
    op.drop_index(op.f('ix_log_files_id'), table_name='log_files')
    op.drop_table('log_files')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_incidents_severity'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_rule_name'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_mitre_technique'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_mitre_tactic'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_id'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_affected_user'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_affected_ip'), table_name='incidents')
    op.drop_table('incidents')
    # ### end Alembic commands ###
